export const GET_ALL_PLAYERS = 'GET_ALL_PLAYERS';
export const INIT_PLAYERS = 'INIT_PLAYERS';
export const FETCH_PLAYERS_FAILED = 'FETCH_PLAYERS_FAILED';

export const FIND_PLAYER = 'FIND_PLAYER';
// export const FILTER_POSITION = 'FILTER_POSITION';
// export const FIND_BY_JERSEY = 'FIND_BY_JERSEY';
